package FinalProject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class Customer extends javax.swing.JFrame {
    
    ResultSet rs = null;
    PreparedStatement pr =null;
    Connection con = null;
    
    public Customer() {
        initComponents();
        con = DB_Connection.connectDB();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        cback = new javax.swing.JButton();
        customerreg = new javax.swing.JButton();
        cuslogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(44, 44, 84));
        jLabel3.setText("Password : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 110, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 44, 84));
        jLabel2.setText("User Name : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 130, 30));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 200, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 200, 30));

        cback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/output-onlinepngtools.png"))); // NOI18N
        cback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbackActionPerformed(evt);
            }
        });
        getContentPane().add(cback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, -1));

        customerreg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerreg.setForeground(new java.awt.Color(132, 129, 122));
        customerreg.setText("Register");
        customerreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerregActionPerformed(evt);
            }
        });
        getContentPane().add(customerreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        cuslogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cuslogin.setForeground(new java.awt.Color(52, 172, 224));
        cuslogin.setText("Log In");
        cuslogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusloginActionPerformed(evt);
            }
        });
        getContentPane().add(cuslogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/23.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbackActionPerformed
        Welcome wel = new Welcome();
        wel.show();
        dispose();
    }//GEN-LAST:event_cbackActionPerformed

    private void customerregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerregActionPerformed
       CustomerReg creg = new CustomerReg();
       creg.show();
       dispose();
    }//GEN-LAST:event_customerregActionPerformed

    private void cusloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusloginActionPerformed
       String query ="select * from registration where User_Name =? and Password = ? ";
           //String query ="select * from TeachTable where username =? and password = ? ";
        
         try {
            pr=con.prepareStatement(query);
            pr.setString(1, jTextField1.getText());
            pr.setString(2, jPasswordField1.getText());
            rs = pr.executeQuery();
            
            int count = 0;
            while(rs.next())
            {
                count++;
                
            }
            if(count==1){
                JOptionPane.showMessageDialog(null, "Logged in successful ");
            }
            else{
                 JOptionPane.showMessageDialog(null, "user name or password is incorrect ");
            }
            rs.close();
            pr.close();
            
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cusloginActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cback;
    private javax.swing.JButton cuslogin;
    private javax.swing.JButton customerreg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
