package FinalProject;

import javax.swing.table.DefaultTableModel;


public class OrderPage extends javax.swing.JFrame {

    /**
     * Creates new form OrderPage
     */
    public OrderPage() {
        initComponents();
    }
    DefaultTableModel model;
    String item;
    String isize;
    int price;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.ButtonGroup();
        size = new javax.swing.ButtonGroup();
        txtqty = new javax.swing.JSpinner();
        txtpayment = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtreturncash = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        remove = new javax.swing.JButton();
        print = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        medium = new javax.swing.JRadioButton();
        large = new javax.swing.JRadioButton();
        small = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        coffee = new javax.swing.JRadioButton();
        pizza = new javax.swing.JRadioButton();
        burger = new javax.swing.JRadioButton();
        sandwich = new javax.swing.JRadioButton();
        icecream = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtqty.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 180, 40));

        txtpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaymentActionPerformed(evt);
            }
        });
        getContentPane().add(txtpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 140, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(248, 239, 186));
        jLabel4.setText("Payment");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 239, 186));
        jLabel3.setText("Total");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 80, -1));

        txtreturncash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreturncashActionPerformed(evt);
            }
        });
        getContentPane().add(txtreturncash, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 140, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(248, 239, 186));
        jLabel5.setText("Return");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 80, -1));

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 140, 40));

        remove.setBackground(new java.awt.Color(18, 137, 167));
        remove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        remove.setForeground(new java.awt.Color(248, 239, 186));
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 180, 40));

        print.setBackground(new java.awt.Color(18, 137, 167));
        print.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        print.setForeground(new java.awt.Color(248, 239, 186));
        print.setText("Print Invoice");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 40));

        add.setBackground(new java.awt.Color(18, 137, 167));
        add.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        add.setForeground(new java.awt.Color(248, 239, 186));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 180, 40));

        table.setBackground(new java.awt.Color(248, 239, 186));
        table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setForeground(new java.awt.Color(51, 0, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Size", "Price", "Qty", "Total"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 460, 280));

        jPanel3.setBackground(new java.awt.Color(248, 239, 186));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        size.add(medium);
        medium.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        medium.setForeground(new java.awt.Color(18, 137, 167));
        medium.setText("Medium");
        jPanel3.add(medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        size.add(large);
        large.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        large.setForeground(new java.awt.Color(18, 137, 167));
        large.setText("Large");
        jPanel3.add(large, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, -1));

        size.add(small);
        small.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        small.setForeground(new java.awt.Color(18, 137, 167));
        small.setText("Small");
        jPanel3.add(small, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 180, 170));

        jPanel2.setBackground(new java.awt.Color(248, 239, 186));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(248, 239, 186));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.add(coffee);
        coffee.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        coffee.setForeground(new java.awt.Color(18, 137, 167));
        coffee.setText("Coffee");
        coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeActionPerformed(evt);
            }
        });
        jPanel2.add(coffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, -1));

        menu.add(pizza);
        pizza.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pizza.setForeground(new java.awt.Color(18, 137, 167));
        pizza.setText("Pizza");
        jPanel2.add(pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, -1));

        menu.add(burger);
        burger.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        burger.setForeground(new java.awt.Color(18, 137, 167));
        burger.setText("Burger");
        jPanel2.add(burger, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, -1));

        menu.add(sandwich);
        sandwich.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sandwich.setForeground(new java.awt.Color(18, 137, 167));
        sandwich.setText("Sandwich");
        sandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandwichActionPerformed(evt);
            }
        });
        jPanel2.add(sandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, -1));

        menu.add(icecream);
        icecream.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        icecream.setForeground(new java.awt.Color(18, 137, 167));
        icecream.setText("Ice Cream");
        icecream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icecreamActionPerformed(evt);
            }
        });
        jPanel2.add(icecream, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 280));

        jPanel1.setBackground(new java.awt.Color(250, 177, 160));
        jPanel1.setForeground(new java.awt.Color(250, 177, 160));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 184, 148));
        jLabel2.setText("Order Your Food");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 300, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        jLabel1.setBackground(new java.awt.Color(250, 177, 160));
        jLabel1.setForeground(new java.awt.Color(162, 155, 254));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalProject/sadf.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 994, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coffeeActionPerformed

    private void icecreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icecreamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icecreamActionPerformed

    private void txtpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaymentActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     
        
        if(pizza.isSelected()==true && small.isSelected()==true){
            item ="Pizza";
            isize ="Small";
            price = 200;
        }
        
        else if(pizza.isSelected()==true && medium.isSelected()==true){
            item ="Pizza";
            isize ="Medium";
            price = 350;
        }
        else if(pizza.isSelected()==true && large.isSelected()==true){
            item ="Pizza";
            isize ="Large";
            price = 500;
        }
        
        else if(burger.isSelected()==true && small.isSelected()==true){
            item ="Burger";
            isize ="Small";
            price = 150;
        }
        
        else if(burger.isSelected()==true && medium.isSelected()==true){
            item ="Burger";
            isize ="Medium";
            price = 200;
        }
        else if(burger.isSelected()==true && large.isSelected()==true){
            item ="Burger";
            isize ="Large";
            price = 300;
        }
        else if(sandwich.isSelected()==true && small.isSelected()==true){
            item ="Sandwich";
            isize ="Small";
            price = 150;
        }
        
        else if(sandwich.isSelected()==true && medium.isSelected()==true){
            item ="Sandwich";
            isize ="Medium";
            price = 200;
        }
        else if(sandwich.isSelected()==true && large.isSelected()==true){
            item ="Sandwich";
            isize ="Large";
            price = 250;
        }
        else if(icecream.isSelected()==true && small.isSelected()==true){
            item ="Ice Cream";
            isize ="Small";
            price = 50;
        }
        
        else if(icecream.isSelected()==true && medium.isSelected()==true){
            item ="Ice Cream";
            isize ="Medium";
            price = 100;
        }
        else if(icecream.isSelected()==true && large.isSelected()==true){
            item ="Ice Cream";
            isize ="Large";
            price = 200;
        }
        else if(coffee.isSelected()==true && small.isSelected()==true){
            item ="Coffee";
            isize ="Small";
            price = 50;
        }
        
        else if(coffee.isSelected()==true && medium.isSelected()==true){
            item ="Coffee";
            isize ="Medium";
            price = 100;
        }
        else if(coffee.isSelected()==true && large.isSelected()==true){
            item ="Coffee";
            isize ="Large";
            price = 200;
        }
        
        
        
        int qty = Integer.parseInt(txtqty.getValue().toString());
        int tot = qty*price;
        
        model = (DefaultTableModel)table.getModel();
        
        model.addRow(new Object[]
            {
                item,
                isize,
                price,
                qty,
                tot
            }
        );
        
        int sum = 0;
        for(int a = 0;a<table.getRowCount();a++){
            sum = sum+Integer.parseInt(table.getValueAt(a,4).toString());
        }
        txttotal.setText(Integer.toString(sum));
        
    }//GEN-LAST:event_addActionPerformed

    private void sandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandwichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sandwichActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        model.removeRow(table.getSelectedRow());
        int sum = 0;
        for(int a = 0;a<table.getRowCount();a++){
            sum = sum+Integer.parseInt(table.getValueAt(a,4).toString());
        }
        txttotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_removeActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtreturncashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreturncashActionPerformed
        
    }//GEN-LAST:event_txtreturncashActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
         int num1 = Integer.parseInt(txttotal.getText());
         int num2 = Integer.parseInt(txtpayment.getText());
         int returncash = num2-num1;
         txtreturncash.setText(Integer.toString(returncash));
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JRadioButton burger;
    private javax.swing.JRadioButton coffee;
    private javax.swing.JRadioButton icecream;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton large;
    private javax.swing.JRadioButton medium;
    private javax.swing.ButtonGroup menu;
    private javax.swing.JRadioButton pizza;
    private javax.swing.JButton print;
    private javax.swing.JButton remove;
    private javax.swing.JRadioButton sandwich;
    private javax.swing.ButtonGroup size;
    private javax.swing.JRadioButton small;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtpayment;
    private javax.swing.JSpinner txtqty;
    private javax.swing.JTextField txtreturncash;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
